server:
  port: 9002
spring:
  application:
    name: file-server
  servlet:
    multipart:
      #开启文件上传
      enabled: true
      #限制文件上传大小为10MB
      max-file-size: 10MB
# MinIO对象存储相关配置
minio:
  #MinIO服务所在地址
  endpoint: http://192.168.17.32:9000
  #存储桶名称
  bucketName: macro2
  #访问的key
  accessKey: minioadmin
  #访问的秘钥
  secretKey: minioadmin