server:
  port: 8087
service-url:
  user-service1: http://localhost:8083
  user-service2: http://localhost:8084
spring:
  cloud:
    gateway:
      routes:
        - id: path_route #路由的ID
          uri: ${service-url.user-service1} #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/user/1

        - id: cookie_route
          uri: ${service-url.user-service2} #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Cookie=username,macro